publishdir = ".."
baseURL = "https://co1ncidence.github.io"
languageCode = "en-us"
title = "nuaNce's blog"
theme = "zozo"
paginate = 10

disqusShortname = ""
googleAnalytics = ""

[author]
  name = "nuaNce"

[params]
   author = "nuaNce"
   description = "Just a place where I can rant and maybe say something smart."
   subTitle = "welcome to my realm."
   dateFormat = "2006-01-02"
   paginationSinglePost = true
   style = "auto-without-switcher"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "Archive"
    identifier = "archive"
    url = "/posts/"
    weight = 3

[social]
  github = "https://www.github.com/co1ncidence/"
  twitter = " "
  facebook = " "
  weibo = " "
  instagram = " "

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
