publishdir = ".."
baseURL = "https://co1ncidence.github.io"
languageCode = "en-us"
title = "nuaNce's blog"
theme = "ezhil"
paginate = 10

disqusShortname = ""
googleAnalytics = ""

[author]
  name = "nuaNce"

[params]
   author = "nuaNce"
   description = "Just a place where I can rant and maybe say something smart"
   subTitle = "welcome to my realm"
   dateFormat = "2006-01-02"
   paginationSinglePost = true
   style = "auto-without-switcher"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "Posts"
    identifier = "archive"
    url = "/posts/"
    weight = 3

[social]
  github = "https://www.github.com/co1ncidence/"
  youtube = "https://www.youtube.com/channel/UCMPEedx3_wzTNd_X1X4SPXg"
  discord = "https://discord.gg/TnJ4h5K"
  reddit = "https://www.reddit.com/user/fps_co1ncidence"

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
