publishdir : ".."
languageCode: "en-us"
baseUrl: "https://co1ncidence.github.io/"
title: "nuaNce's blog"
theme: "anubis"
paginate: 10
disqusShortname: ""
googleAnalytics: ""
enableRobotsTXT: true

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0

menu:
  main:
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 0

params:
  author: ""
  description: ""
  images:
    - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "static" directory
  customJS:
    - js/main.js # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: dark

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown

