publishdir = ".."
baseURL = "https://co1ncidence.github.io"
languageCode = "en-us"
title = "nuaNce"
theme = "jayden"
paginate = 10

[author]
  name = "nuaNce"

[params]
   author = "nuaNce"
   keywords = "blog, linux, ricing"
   description = "Just a place where I rant and sometimes say something smart"
   subTitle = "Welcome To My Realm."
   dateFormat = "2006-01-02"
   paginationSinglePost = true
   customCSS = ["css/style.css"]

[menu]

  [[menu.main]]
    name = "About /"
    identifier = "about"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Posts /"
    identifier = "archive"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Books /"
    identifier = "books"
    url = "/books/"
    weight = 4

  [[menu.main]]
    name = "Software /"
    identifier = "software"
    url = "/software/"
    weight = 2

  [[menu.main]]
    name = "Rices"
    identifier = "rices"
    url = "/rices/"
    weight = 4

[social]
  github = "https://www.github.com/co1ncidence/"
  discord = "https://discord.gg/TnJ4h5K"
  reddit = "https://www.reddit.com/user/fps_co1ncidence"

[taxonomies]
category = "categories"
tag = "tags"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.asciidocExt]
    backend = "html5"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    safeMode = "unsafe"
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    pygmentsUseClasses = true
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokailight"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
