publishdir = ".."
baseURL = "https://co1ncidence.github.io"
languageCode = "en-us"
title = "nuaNce's blog"
theme = "nuance"
paginate = 10

disqusShortname = ""
googleAnalytics = ""

[author]
  name = "nuaNce"

[params]
   author = "nuaNce"
   description = "Just a place where I rant and sometimes say something smart"
   subTitle = "Garfield Hates Monday And So Do I"
   dateFormat = "2006-01-02"
   paginationSinglePost = true
   customCSS = ["css/style.css"]

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About Me -"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "archive"
    name = "Posts -"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Books -"
    identifier = "books"
    url = "/books/"
    weight = 4

  [[menu.main]]
    name = "Rices"
    identifier = "rices"
    url = "/rices/"
    weight = 4

[social]
  github = "https://www.github.com/co1ncidence/"
  discord = "https://discord.gg/TnJ4h5K"
  reddit = "https://www.reddit.com/user/fps_co1ncidence"

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
